project/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.static import serve
from oauth2_provider.urls import management_urlpatterns

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin', RedirectView.as_view(url='admin/', permanent=True)),
    path('admin/', admin.site.urls),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('o/', include((management_urlpatterns, 'oauth2_provider'), namespace='oauth2_provider')),
    path('', include('racetime.urls')),
]

racetime/urls.py
from django.urls import path, include
from oauth2_provider import views as oauth2_views

from . import views

urlpatterns = [
    path('account', views.EditAccount.as_view(), name='edit_account'),
    path('account/', include([
        path('auth', views.LoginRegister.as_view(), name='login_or_register'),
        path('connections', views.EditAccountConnections.as_view(), name='edit_account_connections'),
        path('security', views.EditAccountSecurity.as_view(), name='edit_account_security'),
        path('standing', views.AccountStanding.as_view(), name='account_standing'),
        path('teams', views.EditAccountTeams.as_view(), name='edit_account_teams'),
        path('teams/create', views.CreateTeam.as_view(), name='create_team'),
        path('teams/join/<str:team>', views.JoinTeam.as_view(), name='join_team'),
        path('teams/leave/<str:team>', views.LeaveTeam.as_view(), name='leave_team'),
        path('login', views.Login.as_view(), name='login'),
        path('logout', views.Logout.as_view(), name='logout'),
        path('create', views.CreateAccount.as_view(), name='create_account'),
        path('delete', views.DeleteAccount.as_view(), name='delete_account'),
        path('twitch_auth', views.TwitchAuth.as_view(), name='twitch_auth'),
        path('twitch_disconnect', views.TwitchDisconnect.as_view(), name='twitch_disconnect'),
        path('youtube_auth', views.YouTubeAuth.as_view(), name='youtube_auth'),
        path('youtube_disconnect', views.YouTubeDisconnect.as_view(), name='youtube_disconnect'),
        path('patreon_auth', views.PatreonAuth.as_view(), name='patreon_auth'),
        path('patreon_disconnect', views.PatreonDisconnect.as_view(), name='patreon_disconnect'),
        path('patreon_refresh', views.PatreonRefresh.as_view(), name='patreon_refresh'),
        path('derp', views.PasswordResetView.as_view(), name='password_reset'),
        path('derp/done', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
        path('reset/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('reset/complete', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    ])),

    path('o/', include([
        path('authorize', views.OAuthAuthorize.as_view(), name='oauth2_authorize'),
        path('token', oauth2_views.TokenView.as_view(), name='oauth2_token'),
        path('revoke_token', oauth2_views.RevokeTokenView.as_view(), name='oauth2_revoke'),

        path('delete/<pk>', views.OAuthDeleteToken.as_view(), name='oauth2_delete'),
        path('done', views.OAuthDone.as_view(), name='oauth2_authorize_done'),
        path('userinfo', views.OAuthUserInfo.as_view(), name='oauth2_userinfo'),
        path('<str:category>/data', views.OAuthCategoryData.as_view(), name='oauth2_category_data'),
        path('<str:category>/startrace', views.OAuthCreateRace.as_view(), name='oauth2_create_race'),
        path('<str:category>/<str:race>/edit', views.OAuthEditRace.as_view(), name='oauth2_edit_race'),
        path('<str:category>/<str:race>/monitor/pin/<str:message>', views.OAuthRaceChatPin.as_view(), name='oauth2_chat_pin'),
        path('<str:category>/<str:race>/monitor/unpin/<str:message>', views.OAuthRaceChatUnpin.as_view(), name='oauth2_chat_unpin'),
        path('<str:category>/<str:race>/monitor/purge/<str:message>', views.OAuthRaceChatPurge.as_view(), name='oauth2_chat_purge'),
        path('<str:category>/<str:race>/monitor/delete/<str:message>', views.OAuthRaceChatDelete.as_view(), name='oauth2_chat_delete'),
    ])),

    path('team/', include([
        path('<str:team>.json', views.TeamData.as_view()),
        path('<str:team>', views.Team.as_view(), name='team'),
        path('<str:team>/', include([
            path('data', views.TeamData.as_view(), name='team_data'),
            path('manage/', include([
                path('edit', views.EditTeam.as_view(), name='edit_team'),
                path('delete', views.DeleteTeam.as_view(), name='delete_team'),
                path('members', views.TeamMembers.as_view(), name='team_members'),
                path('members/add', views.AddTeamMember.as_view(), name='team_member_add'),
                path('members/remove', views.RemoveTeamMember.as_view(), name='team_member_remove'),
                path('members/add-owner', views.AddTeamOwner.as_view(), name='team_owner_add'),
                path('members/remove-owner', views.RemoveTeamOwner.as_view(), name='team_owner_remove'),
                path('log', views.TeamAudit.as_view(), name='team_audit_log'),
            ])),
        ])),
    ])),

    path('autocomplete/', include([
        path('user', views.AutocompleteUser.as_view(), name='autocomplete_user'),
    ])),

    path('', views.Home.as_view(), name='home'),
    path('search', views.Search.as_view(), name='search'),
    path('request_category', views.RequestCategory.as_view(), name='request_category'),
    path('races/data', views.RaceListData.as_view(), name='race_list_data'),
    path('races.json', views.RaceListData.as_view()),
    path('user/search', views.AutocompleteUser.as_view(), name='autocomplete_user'),
    path('user/<str:user>', views.ViewProfile.as_view(), name='view_profile'),
    path('user/<str:user>.json', views.UserProfileData.as_view()),
    path('user/<str:user>/', include([
        path('data', views.UserProfileData.as_view(), name='user_profile_data'),
        path('races/data', views.UserRaceData.as_view(), name='user_race_list_data'),
        path('races.json', views.UserRaceData.as_view()),
    ])),
    path('user/<str:user>/<str:name>', views.ViewProfile.as_view(), name='view_profile'),

    path('categories/data', views.CategoryListData.as_view(), name='category_list_data'),
    path('<str:category>.json', views.CategoryData.as_view()),
    path('<str:category>', views.Category.as_view(), name='category'),
    path('<str:category>/', include([
        path('data', views.CategoryData.as_view(), name='category_data'),
        path('races/data', views.CategoryRaceData.as_view(), name='category_race_list_data'),
        path('races.json', views.CategoryRaceData.as_view()),
        path('manage/', include([
            path('edit', views.EditCategory.as_view(), name='edit_category'),
            path('deactivate', views.DeactivateCategory.as_view(), name='category_deactivate'),
            path('reactivate', views.ReactivateCategory.as_view(), name='category_reactivate'),
            path('goals', views.GoalList.as_view(), name='category_goals'),
            path('goals/new', views.CreateGoal.as_view(), name='new_category_goal'),
            path('goals/<str:goal>/edit', views.EditGoal.as_view(), name='edit_category_goal'),
            path('bots', views.BotList.as_view(), name='category_bots'),
            path('bots/new', views.CreateBot.as_view(), name='new_category_bot'),
            path('bots/<str:bot>/deactivate', views.DeactivateBot.as_view(), name='deactivate_category_bot'),
            path('bots/<str:bot>/reactivate', views.ReactivateBot.as_view(), name='reactivate_category_bot'),
            path('mods', views.CategoryModerators.as_view(), name='category_mods'),
            path('mods/add_owner', views.AddOwner.as_view(), name='category_owners_add'),
            path('mods/remove_owner', views.RemoveOwner.as_view(), name='category_owners_remove'),
            path('mods/add_moderator', views.AddModerator.as_view(), name='category_mods_add'),
            path('mods/remove_moderator', views.RemoveModerator.as_view(), name='category_mods_remove'),
            path('teams', views.CategoryTeams.as_view(), name='category_teams'),
            path('log', views.CategoryAudit.as_view(), name='category_audit_log'),
            path('emotes', views.CategoryManageEmotes.as_view(), name='category_emotes'),
            path('emotes/add', views.AddEmote.as_view(), name='category_emotes_add'),
            path('emotes/<str:emote_name>/remove', views.RemoveEmote.as_view(), name='category_emotes_remove'),
        ])),
        path('leaderboards', views.CategoryLeaderboards.as_view(), name='leaderboards'),
        path('leaderboards/data', views.CategoryLeaderboardsData.as_view(), name='leaderboards_data'),
        path('leaderboards.json', views.CategoryLeaderboardsData.as_view()),
        path('emotes', views.CategoryEmotes.as_view(), name='category_list_emotes'),
        path('record', views.CategoryRecorder.as_view(), name='category_record'),
        path('startrace', views.CreateRace.as_view(), name='create_race'),
        path('star', views.FavouriteCategory.as_view(), name='star'),
        path('unstar', views.UnfavouriteCategory.as_view(), name='unstar'),
    ])),

    path('<str:category>/<str:race>.csv', views.RaceCSV.as_view()),
    path('<str:category>/<str:race>.json', views.RaceData.as_view()),
    path('<str:category>/<str:race>.log', views.RaceChatLog.as_view()),
    path('<str:category>/<str:race>.txt', views.RaceChatLog.as_view()),
    path('<str:category>/<str:race>', views.Race.as_view(), name='race'),
    path('<str:category>/<str:race>/', include([
        path('csv', views.RaceCSV.as_view(), name='race_csv'),
        path('data', views.RaceData.as_view(), name='race_data'),
        path('mini', views.RaceMini.as_view(), name='race_mini'),
        path('livesplit', views.RaceLiveSplit.as_view(), name='race_livesplit'),
        path('log', views.RaceChatLog.as_view(), name='race_log'),
        path('renders', views.RaceRenders.as_view(), name='race_renders'),
        path('spectate', views.RaceSpectate.as_view(), name='race_spectate'),

        path('message', views.Message.as_view(), name='message'),
        path('get_dm/<str:message>', views.RaceChatDM.as_view(), name='chat_dm'),
        path('join', views.Join.as_view(), name='join'),
        path('leave', views.Leave.as_view(), name='leave'),
        path('request_invite', views.RequestInvite.as_view(), name='request_invite'),

racetime/views/api/urls.py
from django.urls import path

from . import CategoryViewSet, CategoryStatsViewSet

app_name = 'racetime_api'
urlpatterns = [
    path('categories', CategoryViewSet.as_view({'get': 'list', 'post': 'create'}), name="category-list"),
    path('categories/stats', CategoryStatsViewSet.as_view({'get': 'list'}), name='category-stats-list'),
    path('categories/<str:slug>', CategoryViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'patch': 'partial_update',
        'delete': 'destroy'
    }), name="category-detail"),
    path('categories/<str:slug>/stats', CategoryStatsViewSet.as_view({'get': 'retrieve'}), name='category-stats-detail'),
]

racetime/models/admin.py
from django.db import models

from ..utils import get_hashids


class Bulletin(models.Model):
    """
    Bulletins are short messages shown at the top of every page.

    Used for announcements and so on. The `message` field accepts raw HTML.
    """
    visible_from = models.DateTimeField()
    visible_to = models.DateTimeField()
    message = models.TextField()
    class_names = models.CharField(
        max_length=255,
        blank=True,
        help_text='Space-separated CSS class names, e.g. "highlight".'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        indexes = [
            models.Index(fields=['visible_from', 'visible_to']),
        ]

    @property
    def hashid(self):
        return get_hashids(self.__class__).encode(self.id)

    def __str__(self):
        return self.visible_from.strftime('%Y-%m-%d') + ' – ' + self.message[:50]

racetime/models/bot.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from oauth2_provider.settings import oauth2_settings

from ..utils import get_hashids


class Bot(models.Model):
    """
    A category bot.

    Bots are associated to an OAuth2 application, which provides credentials
    allowing an external program to authenticate against the site. When authed,
    the program may perform certain actions on races within the bot's category,
    such as posting chat messages and changing race information.
    """
    application = models.ForeignKey(
        oauth2_settings.APPLICATION_MODEL,
        on_delete=models.PROTECT,
        null=True,
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
    )
    active = models.BooleanField(
        default=True,
        db_index=True,
    )
    name = models.CharField(
        max_length=25,
        db_index=True,
        help_text=(
            'Public name for this bot (3-25 characters). Must be unique, and '
            'may not contain # or @ characters.'
        ),
        validators=[
            MinLengthValidator(3),
            RegexValidator(
                regex=r'[\x00@#]',
                message='Name cannot contain @ or #',
                inverse_match=True,
            ),
        ],
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    deactivated_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['category', 'name'],
                name='unique_name_per_category',
            ),
        ]

    @property
    def hashid(self):
        return get_hashids(self.__class__).encode(self.id)

    def __str__(self):
        return self.name

racetime/admin/forms.py
from django import forms
from django.db.models import Count

from racetime.models import Goal


class RaceForm(forms.ModelForm):
    goal = forms.ModelChoiceField(
        empty_label='Custom',
        help_text='Select a goal for this race, or use a custom goal.',
        queryset=Goal.objects.filter(active=True).annotate(
            num_races=Count('race__id'),
        ).order_by('-num_races', 'name'),
        required=False,
        blank=True,
        widget=forms.RadioSelect,
    )

    class Meta:
        widgets = {
            'recordable': forms.HiddenInput,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance and 'goal' in self.fields:
            self.fields['goal'].queryset = self.fields['goal'].queryset.filter(
                category=instance.category,
            )

    def clean(self):
        cleaned_data = super().clean()

        if 'goal' in self.fields:
            if not cleaned_data.get('goal') and not cleaned_data.get('custom_goal'):
                raise forms.ValidationError('You need to set a goal for this race.')

            if cleaned_data.get('goal') and cleaned_data.get('custom_goal'):
                raise forms.ValidationError('The race must only have one goal.')

        if cleaned_data.get('custom_goal'):
            cleaned_data['recordable'] = False
        else:
            cleaned_data['recordable'] = cleaned_data.get('ranked')

        return cleaned_data

racetime/views/autocomplete.py
import operator
from functools import reduce

from django import http
from django.db.models import Q
from django.views import generic

from racetime import models


class AutocompleteMixin:
    filter_kwargs = ('name',)
    kwargs = NotImplemented
    queryset = NotImplemented
    result_count = 10

    def clean_term(self, term):
        return str(term).strip()

    def get(self, request, *args, **kwargs):
        # Get terms
        term = self.clean_term(request.GET.get('term', ''))
        name = self.clean_term(request.GET.get('name', ''))
        scrim = self.clean_term(request.GET.get('discriminator', ''))

        # Validate the type of search type we are doing. Defaults to term
        if name and scrim:
            term = name + "#" + scrim
        elif name and not scrim:
            term = name
        elif scrim and not name:
            term = "#" + scrim

        # Build up a dict response based on our query term
        builtresponse = []
        if term:
            results = self.get_results(term)
            for result in results:
                builtresponse.append(self.item_from_result(result))

        return http.JsonResponse({
            'results': builtresponse,
        })

    def get_results(self, term):
        queryset = self.queryset
        queryset = queryset.filter(reduce(operator.or_, [
            Q(**{k + '__istartswith': term})
            for k in self.filter_kwargs
        ]))
        return queryset[:self.result_count]

    def item_from_result(self, result):
        return {
            'value': str(result),
        }


class AutocompleteUser(generic.View, AutocompleteMixin):
    filter_kwargs = ('name',)
    queryset = models.User.objects.filter_active()

    def get_results(self, term):
        queryset = self.queryset

        if '#' in term:
            name, scrim = term.split('#', 1)
        else:
            name = term
            scrim = None

        if name:
            queryset = queryset.filter(name__istartswith=name)
        if scrim:
            queryset = queryset.filter(discriminator=scrim)

        return queryset

    def item_from_result(self, result):
        return result.api_dict_summary()

racetime/templates/racetime/bot_list.html
{% extends 'racetime/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'racetime/style/bot_list.css' %}">
{% endblock %}

{% block title %}
    Manage bots | {{ category.name }} |
{% endblock %}

{% block main %}
    <ol class="breadcrumbs">
        <li><a href="{{ category.get_absolute_url }}">{{ category.slug }}</a></li>
        <li><a href="{% url 'category_bots' category=category.slug %}">bots</a></li>
    </ol>
    <h2>{{ category }}</h2>
    {% include 'racetime/category/manage_tabs.html' with current='category_bots' %}
    <h3>Manage bots</h3>
    <p>
        This page allows you to set up client credentials for bot users to interact
        with any {{ category.short_name }} race room. For more details on how
        category bots work and how to start writing your own, please read our
        <a href="https://github.com/racetimeGG/racetime-app/wiki/Category-bots">bot documentation guide</a>
        on GitHub.
    </p>
    <h3>Active bots</h3>
    <p class="help">
        All bot users that can currently interact with your category's races.
    </p>
    <ol class="bot-list">
        {% for bot in view.active_bots %}
            <li id="bot-{{ bot.hashid }}">
                <dl>
                    <dt>Name</dt>
                    <dd class="name">
                        <span>{{ bot.name }}</span>
                        <form action="{% url 'deactivate_category_bot' bot=bot.hashid category=category.slug %}" method="post">
                            {% csrf_token %}
                            <button class="btn dangerous" type="submit">Deactivate</button>
                        </form>
                    </dd>
                    <dt class="copy-to-clipboard" data-target="#bot-{{ bot.hashid }} .client-id"
                        title="Click to copy the client ID to your clipboard">
                        <span>Client ID</span>
                        <i class="material-icons">assignment</i>
                    </dt>
                    <dd class="client-id copy-to-clipboard">{{ bot.application.client_id }}</dd>
                    <dt class="copy-to-clipboard" data-target="#bot-{{ bot.hashid }} .secret"
                        title="Click to copy the client secret to your clipboard">
                        <span>Client secret</span>
                        <i class="material-icons">assignment</i>
                    </dt>
                    <dd class="secret copy-to-clipboard">
                        <span>{{ bot.application.client_secret }}</span>
                    </dd>
                </dl>
            </li>
        {% empty %}
            <li>
                You do not have any active bots in this category.
            </li>
        {% endfor %}
    </ol>
    <h3>Inactive bots</h3>
    <p class="help">
        Inactive bots cannot perform any actions on races, but are kept visible
        for any messages they may have sent prior to deactivation. You can
        re-activate a bot to reclaim usage of its name, however its original
        client credentials will not be retained.
    </p>
    <ol class="bot-list">
        {% for bot in view.inactive_bots %}
            <li>
                <dl>
                    <dt>Name</dt>
                    <dd class="name">
                        <span>{{ bot.name }}</span>
                        <form action="{% url 'reactivate_category_bot' bot=bot.hashid category=category.slug %}" method="post">
                            {% csrf_token %}
                            <button class="btn" type="submit">Reactivate</button>
                        </form>
                    </dd>
                </dl>
            </li>
        {% empty %}
            <li>
                You do not have any inactive bots in this category.
            </li>
        {% endfor %}
    </ol>
    <h3>Create new bot</h3>
    {% if view.available_bots > 0 %}
        <p class="help">
            Authorize a new bot account in this category, allowing you to set
            up a third-party application that can interact with races. Please
            see the documentation guide on how to use bots to get started.
        </p>
        <p>
            You can create <strong>{{ view.available_bots }}</strong> more
            bot{{ view.available_bots|pluralize }} for {{ category.short_name }}.
        </p>
        <form class="bot-form layout-form" action="{% url 'new_category_bot' category=category.slug %}" method="post">
            {% csrf_token %}
            <ul>{{ bot_form.as_ul }}</ul>
            <button class="btn" type="submit">Create</button>
        </form>
    {% else %}
        <p>
            You have reached the maximum number of active bot users for this
            category. To create another, you must first deactivate an existing
            bot.
        </p>
    {% endif %}
{% endblock %}

racetime/templates/racetime/category_emotes.html
{% extends 'racetime/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'racetime/style/emote_list.css' %}">
{% endblock %}

{% block title %}
    Emotes | {{ category.name }} |
{% endblock %}

{% block main %}
    <ol class="breadcrumbs">
        <li><a href="{{ category.get_absolute_url }}">{{ category.slug }}</a></li>
        <li><a href="{% url 'category_emotes' category=category.slug %}">emotes</a></li>
    </ol>
    <h2>{{ category }}</h2>
    {% include 'racetime/category/manage_tabs.html' with current='category_emotes' %}
    <h3>Emotes</h3>
    <p>
        Manage emotes that can be used in this category. Any emotes you upload
        here must abide by our rules, be less than 16kb in size and below 54x54
        pixels.
    </p>
    <ul class="emote-list">
        {% for emote in current_emotes %}
            <li>
                <img src="{{ emote.image.url }}" alt="">
                <span class="name">{{ emote.name }}</span>
                <form action="{% url 'category_emotes_remove' category=category.slug emote_name=emote.name %}" method="post">
                    {% csrf_token %}
                    <button class="btn dangerous" type="submit">Remove</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    {% if available_emotes > 0 %}
        <h3>Add a new emote</h3>
        <p class="help">You can add up to {{ available_emotes }} more emote{{ available_emotes|pluralize }}.</p>
        <form class="add-emote-form layout-form" action="{% url 'category_emotes_add' category=category.slug %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <ul>{{ add_form.as_ul }}</ul>
            <button class="btn" type="submit">Add emote</button>
        </form>
    {% else %}
        <p>
            You have reached the maximum number of emotes for this
            category. To add more, you must first delete an existing emote.
        </p>
    {% endif %}
{% endblock %}

racetime/templates/racetime/category_leaderboards.html
{% extends 'racetime/base.html' %}

{% block title %}
    {{ category.name }} (leaderboards) |
{% endblock %}
{% block meta %}
    <meta property="og:title" content="Leaderboards for {{ category.name }}">
    <meta name="description" content="Current user rankings for {{ category.short_name }} races.">
    <meta property="og:description" content="Current user rankings for {{ category.short_name }} races.">
    {% if meta_image %}
        <meta property="og:image" content="{{ meta_image }}">
    {% endif %}
{% endblock %}

{% block main %}
    {% include 'racetime/category/intro.html' %}
    {% include 'racetime/category/tabs.html' with current=current_tab %}
    <h3>Leaderboards</h3>
    <div class="search-filter" style="margin-top: 10px">
        <ul>
        <li class="label">Sort by:</li>
            <li>
                {% if sort == 'score' %}
                    <span>Score</span>
                {% else %}
                    <a href="{% url 'leaderboards' category=category.slug %}{% if leaderboards.number > 1 %}?page={{ leaderboards.number }}{% endif %}">Score</a>
                {% endif %}
            </li>
            <li>
                {% if sort == 'best_time' %}
                    <span>Best time</span>
                {% else %}
                    <a href="{% url 'leaderboards' category=category.slug %}?{% if leaderboards.number > 1 %}page={{ leaderboards.number }}&{% endif %}sort=best_time">Best time</a>
                {% endif %}
            </li>
            <li>
                {% if sort == 'times_raced' %}
                    <span>Races entered</span>
                {% else %}
                    <a href="{% url 'leaderboards' category=category.slug %}?{% if leaderboards.number > 1 %}page={{ leaderboards.number }}&{% endif %}sort=times_raced">Races entered</a>
                {% endif %}
            </li>
        </ul>
    </div>
    <p class="help">
        Note: leaderboards are currently in beta. The ranking algorithm is,
        well, a bit of a potato. A more well thought-out calculation system
        will be implemented later, but you can get a feel for general race
        performance with the scoring below.
    </p>
    <div class="category-leaderboards">
        {% if sort != 'score' %}
            {% include 'racetime/pops/paginator.html' with page=leaderboards query='sort='|add:sort %}
        {% else %}
            {% include 'racetime/pops/paginator.html' with page=leaderboards %}
        {% endif %}
        <ol>
            {% for goal, rankings in leaderboards %}
                <li>
                    {% include 'racetime/category/leaderboard.html' %}
                </li>
            {% endfor %}
        </ol>
        {% if sort != 'score' %}
            {% include 'racetime/pops/paginator.html' with page=leaderboards query='sort='|add:sort %}
        {% else %}
            {% include 'racetime/pops/paginator.html' with page=leaderboards %}
        {% endif %}
    </div>
{% endblock %}

racetime/templates/racetime/category_teams.html
{% extends 'racetime/base.html' %}

{% block title %}
    Manage team access | {{ category.name }} |
{% endblock %}

{% block main %}
    <ol class="breadcrumbs">
        <li><a href="{{ category.get_absolute_url }}">{{ category.slug }}</a></li>
        <li><a href="{% url 'category_teams' category=category.slug %}">teams</a></li>
    </ol>
    <h2>{{ category }}</h2>
    {% include 'racetime/category/manage_tabs.html' with current='category_teams' %}
    <h3>Manage team access</h3>
    <p>
        Control teams that have special access to this category. Teams that you
        select here will be able to bypass certain restrictions on the category,
        e.g. being able to create multiple race rooms.
    </p>
    <p>
        You do not need to add access for a team to be able to race in this
        category. Typically, you should only add access for teams involved in
        things like tourney admin, stream organization and so on.
    </p>
    <form class="category-teams-form layout-form" method="post">
        {% csrf_token %}
        <ul>{{ form.as_ul }}</ul>
        <button class="btn" type="submit">Submit</button>
    </form>
{% endblock %}

racetime/templates/racetime/team_form.html
{% extends 'racetime/base.html' %}

{% block title %}
    {% if team %}
    Edit team
    {% else %}
    Create new team
    {% endif %}
{% endblock %}

{% block js %}
    {% if not team %}
        <script>
        $(function() {
            var changedSlug = false;
            $(document).on('change', '#id_slug', function() {
                changedSlug = $(this).val() !== '';
            });
            $(document).on('blur', '#id_name', function() {
                var $slug = $('#id_slug');
                var nameVal = $(this).val()
                var slugVal = $slug.val();
                if (!nameVal || (slugVal && changedSlug)) return;
                $slug.val(nameVal
                    .toLowerCase()
                    .replace(/\s+/g, '-')
                    .replace(/&/g, '-and-')
                    .replace(/[^\w\-]+/g, '')
                    .replace(/--+/g, '-')
                    .replace(/^-+/, '')
                    .replace(/-+$/, '')
                );
            });
        });
        </script>
    {% endif %}
{% endblock %}

{% block main %}
    {% if team %}
        <ol class="breadcrumbs">
            <li><a href="{{ team.get_absolute_url }}">{{ team.slug }}</a></li>
            <li><a href="{% url 'edit_team' team=team.slug %}">edit</a></li>
        </ol>
        <h2>{{ team }}</h2>
        {% include 'racetime/team/manage_tabs.html' with current='edit_team' %}
        <h3>Edit team</h3>
    {% else %}
        <h2>Create new team</h2>
    {% endif %}
    <form class="team-form layout-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>{{ form.as_ul }}</ul>
        <button class="btn" type="submit">Submit</button>
    </form>
    {% if team %}
        <h3 class="dangerous">
            Dissolve team
        </h3>
        <p class="help">
            This will permanently dissolve your team. This action <b>cannot</b> be undone!
            Make sure you're really really sure you really want to do this. Really.
        </p>
        <form class="layout-form dangerous" action="{% url 'delete_team' team=team.slug %}" method="post">
            {% csrf_token %}
            <ul>{{ delete_form.as_ul }}</ul>
            <button class="btn" type="submit">Dissolve team</button>
        </form>
    {% endif %}
{% endblock %}